version: '2'

networks:
  torrent:
    driver: bridge

services:
  rtorrent:
    image: xataz/rtorrent
    environment:
      - UID=1000
      - GID=1000
      - VIRTUAL_HOST=rtorrent.domain.com 
      - LETSENCRYPT_HOST=rtorrent.domain.com 
      - LETSENCRYPT_EMAIL=toto@yopmail.fr
    tty: true
    networks:
      - torrent

  flood:
    image: xataz/flood
    environment:
      - UID=1000
      - GID=1000
      - RTORRENT_HOST=rtorrent.gallardo93.com
      - RTORRENT_PORT=5000
      - FLOOD_SECRET=flood	
    ports:
      - "3000:3000"
    networks:
      - torrent
