rutorrent:
  image: wonderfall/rtorrent-flood
  environment:
    - FLOOD_SECRET=mysupersecretkey
    - VIRTUAL_HOST=rtorrent.domain.com
    - LETSENCRYPT_HOST=rtorrent.domain.com
    - LETSENCRYPT_EMAIL=toto@yopmail.fr
    - "3000:3000"
    - "49184:49184"
  volumes:
    - /srv/docker/cont_rtorrent/torrents:/data
