plex:
    container_name: plex
    image: timhaak/plex
    ports:
        - "32400:32400"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./data/config:/config
        - ./data/data:/data
    environment:
        - PLEX_USERNAME=username
        - PLEX_PASSWORD=password
        - PLEX_TOKEN=token
        - VIRTUAL_HOST=plex.domain.com 
        - LETSENCRYPT_HOST=plex.domain.com 
        - LETSENCRYPT_EMAIL=toto@yopmail.fr
plexpy:
    container_name: "plexpy"
    image: dbarton/plexpy
    volumes:
        - ./data/data:/datadir
    ports:
        - "8181:8181"
