flarum: 
  image: mondedie/docker-flarum:0.1.0-beta.6-stable 
  container_name: flarum 
  links: 
    - mariadb:mariadb 
  environment: 
    - FORUM_URL=https://flarum.gallardo93.com 
    - DB_PASS=mypassword
    - VIRTUAL_HOST=flarum.domain.com 
    - LETSENCRYPT_HOST=flarum.domain.com 
    - LETSENCRYPT_EMAIL=toto@yopmail.fr
  volumes: 
    - /mnt/docker/flarum/assets:/flarum/app/assets 
    - /mnt/docker/flarum/extensions:/flarum/app/extensions 

mariadb: 
  image: mariadb 
  container_name: mariadb 
  volumes: 
    - /mnt/docker/mysql/db:/var/lib/mysql 
  environment: 
    - MYSQL_ROOT_PASSWORD=mypassword 
    - MYSQL_DATABASE=flarum 
    - MYSQL_USER=flarum 
    - MYSQL_PASSWORD=mypassword
