version: '3'

services:
    
  traefik:
    image: traefik:latest
    command: --web --web.address=:8080 --docker --docker.domain=dockerpoc.domain.org --docker.watch --logLevel=DEBUG \
            --entryPoints='Name:http Address::80' --defaultEntryPoints='http' --accessLogsFile='log/access.log'
    hostname: traefik
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:dockerpoc.domain.org"
      - "traefik.backend.port=8080"
      - "traefik.frontend.entryPoints=http"
    networks:
      - bca_int 

  portainer:
    image: portainer/portainer
    hostname: portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:dockerpoc.domain.org;PathPrefixStrip:/portainer"
      - "traefik.backend.port=9000"
      - "traefik.frontend.entryPoints=http" 
    networks:
      - int

networks:
  int:
    external:
     name: int
